### ISSUE TITLE
PC_version/dateRange.css文件乱码

### ISSUE THREAD

**Issue by lbp0200** [johnnyzheng/DatePicker#3]
``` css
.calendar-month tbody td {
    line-height: 30px;
    padding: 4px 11px;
    text-align: center;
    white-space: nowrap;
    font-family: "΢���ź�";
    cursor: pointer;
}
```
